server:
  port: 8001
akylino:
  aws:
    region: us-east-1
    dynamodb:
      endpoint: http://dynamodb.us-east-1.amazonaws.com
    secretsmanager:
      endpoint: https://secretsmanager.us-east-1.amazonaws.com
      secretName: DevAccessSecretTrial