package com.akylino.infrastructure.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "customers")
public class CustomerEntity {

    //    @DynamoDBAutoGeneratedKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    //    @DynamoDBAttribute(attributeName = "customerFullName")
    private String customerFullName;

    //    @DynamoDBAttribute(attributeName = "age")
    private Integer age;

    //    @DynamoDBAttribute(attributeName = "birthName")
    private String birthName;

    //    @DynamoDBAttribute(attributeName = "telephoneContact")
    private String telephoneContact;

    //    @DynamoDBAttribute(attributeName = "addressPrincipal")
    private String addressPrincipal;

    //    @DynamoDBAttribute(attributeName = "addressSecond")
    private String addressSecond;

    //    @DynamoDBAttribute(attributeName = "activeFlag")
    private Boolean activeFlag;
}
